# Generated by Django 4.1 on 2022-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search_TJAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia', models.IntegerField(choices=[(1, '-Elige la instancia-'), (2, 'Juzgado'), (3, 'Salas Administrativas'), (4, 'Amparo')], default=1)),
                ('numero', models.IntegerField(choices=[(1, '-Elige la instancia-'), (2, 'Juzgado'), (3, 'Salas Administrativas'), (4, 'Amparo')], default=1)),
                ('tipo', models.IntegerField(choices=[(1, '-Elige la instancia-'), (2, 'Juzgado'), (3, 'Salas Administrativas'), (4, 'Amparo')], default=1)),
                ('expediente', models.IntegerField()),
                ('fecha', models.IntegerField()),
            ],
        ),
    ]
