# Generated by Django 4.1 on 2022-11-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tjam_tipo',
            name='numero',
        ),
    ]
