# Generated by Django 4.1 on 2022-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_tjam_tipo_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGRARIOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribunal', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tribunales_AGRARIOS',
            },
        ),
    ]
