# Generated by Django 4.1 on 2022-11-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_agrarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AGRARIOS',
            new_name='Tribunales_AGRARIOS',
        ),
        migrations.RenameField(
            model_name='tribunales_agrarios',
            old_name='tribunal',
            new_name='nombre',
        ),
    ]
