# Generated by Django 4.1 on 2022-12-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areas_Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas_Salas',
            },
        ),
        migrations.CreateModel(
            name='distrito_Juzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'distrito_Juzgados',
            },
        ),
        migrations.CreateModel(
            name='areas_Juzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STEJEM.distrito_juzgado')),
            ],
            options={
                'db_table': 'areas_Juzgados',
            },
        ),
    ]
