# Generated by Django 4.1 on 2022-12-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STEJEM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas_juzgado',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
