# Generated by Django 4.1 on 2022-12-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CJF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='organo_Jurisdiccional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CJF.circuito')),
            ],
            options={
                'db_table': 'OrganosJurisdiccionales_CJF',
            },
        ),
    ]
