# Generated by Django 4.1 on 2022-12-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customer_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='imagen',
            field=models.ImageField(default='static/assets/user/25profile_default.png', upload_to='./static/assets/user'),
        ),
    ]
