# Generated by Django 4.1 on 2022-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customer_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='imagen',
            field=models.ImageField(blank=True, default='static/assets/user/25profile_default.png', null=True, upload_to='static/assets/user/'),
        ),
    ]
