# Generated by Django 4.1 on 2022-12-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TJAM_instancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instancias_de_TJAM',
            },
        ),
        migrations.CreateModel(
            name='TJAM_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TJAM.tjam_instancia')),
            ],
            options={
                'db_table': 'tipo_de_TJAM',
            },
        ),
        migrations.CreateModel(
            name='TJAM_numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TJAM.tjam_instancia')),
            ],
            options={
                'db_table': 'numero_de_TJAM',
            },
        ),
    ]
